# Generated by Django 2.1.5 on 2019-02-03 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('überschrift', models.TextField(max_length=50)),
                ('inhalt', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, max_length=10)),
            ],
        ),
    ]
